### ISSUE TITLE
SlackAPIクラスのドキュメンテーションコメント

### ISSUE THREAD

**Issue by yukihiroyamaguchi569** [yukihiroyamaguchi569/GAS_convinient_scheduler#3]
前回作成したSlackAPIクラスのドキュメンテーションコメントをお願いします。

**Comment by yukihiroyamaguchi569** [comment]
70行目からのコメントがコピペのままになっているような気がします。
168行目 getSlackNameValuesById 関数のドキュメンテーションコメントをお願いします。

**Comment by yukihiroyamaguchi569** [comment]
ブランチは
feature/#3_make_documentation_comments
を使ってくださいー。
よろしくお願いします

**Comment by ymgcmnk** [comment]
@yukihiroyamaguchi569 
@etau 
@umehara0506 

人生初プッシュしてみます。たぶん。

ドキュメンテーションコメント4点追加しました。
行数は修正後のものです。

**＜山口さんからご指定のあった2点＞**
68行　getMembersValues
166行　getSlackNameValuesById


**＜追加2点＞**
要らんかもですが、下記についてもドキュメンテーションコメント入れました。
8行　getActiveChannelsValues
182行　function testSlackApi



**＜その他の修正＞**
・各関数前後の空白は1行に統一。
・各関数内の空白行はトルツメ。


**＜？＞**
function testSlackApi　もドキュメンテーションコメント必要？


以上！合ってるのか不安！

※#3_make_documentation_comments はpull＆pushできなかったため、　main　にpushしました。

**Comment by yukihiroyamaguchi569** [comment]
@ymgcmnk  ありがとうございました。
上手く行ったようです。
Issue#3は閉じますね〜。
